### ISSUE TITLE
Help with AC3D export for SolveSpace

### ISSUE THREAD

**Issue by Symbian9** [NikolaiVChr/Blender-AC3D#1]
Please, help with AC3D mesh export for SolveSpace 2d/3d CAD!
* https://github.com/solvespace/solvespace

Here is issue on SolveSpace issue tracker
* https://github.com/solvespace/solvespace/issues/30

Currently SolveSpace already include OBJ, STL and ThreeJS mesh export code:
* https://github.com/whitequark/solvespace/blob/master/src/export.cpp

Source code mostly in C and C++:
* https://github.com/whitequark/solvespace/blob/master/src/

**Comment by NikolaiVChr** [comment]
I don't code in C anymore, sorry.
