### ISSUE TITLE
Installation not working on 2.80 (W7) and 2.81 (Ubuntu)

### ISSUE THREAD

**Issue by PSX59** [NikolaiVChr/Blender-AC3D#14]
Hello Nikolai,
I want to install this plugin for blender 2.8+ but after installation I can't show it in the blender's plugin list (edit/preferences).
It was automatically well copied by install function and it is present in the folder beside over activated plugins.
I made the test on Win7/blender 2.80 and Ubuntu/blender 2.81, same issue.
Is it a problem on my side ?
Thanks in advance for your answer.

Vincent

**Comment by NikolaiVChr** [comment]
The auto install function don't work with this plugin.

First thing is to make sure you download the 2.80 branch. On the homepage of this plugin there is a dropdown button that says branch, make sure it says 2.80.

This is the install procedure:
Open the blender/x.x/scripts/addons folder, then pull the io_scene_ac3d folder into the addons folder of blender. There's an alternative location you can drop it, at ~/.blender/x.x/scripts/addons (linux) or c:\Users[username]\AppData\Roaming\Blender Foundation\Blender\x.x\scrips\addons (Windows 7+), where x.x is the version of Blender and [username] is the Windows user name. Notice AppData per default is hidden in Windows, but you can just write it in the address bar.

**Comment by PSX59** [comment]
Thanks so much Nikolaï,
That works manually. I can now activate it.
I saw Installation instructions in 2.80 branch but there's no warning concerning the fact that is not compatible with auto install function. Could you add a note for this in the main page for other people ?
Many thanks for your help and for giving me, with this plugin, the opportunity to create an AC3D model of my plane in Blender 2.80.
FlightGear will be happy   : )

Vincent
