### ISSUE TITLE
Blender 2.82？

### ISSUE THREAD

**Issue by sidi762** [NikolaiVChr/Blender-AC3D#19]
In Blender 2.82 it said ModuleNotFoundError when trying to enable from settings.

**Comment by NikolaiVChr** [comment]
Did you download the 2.80 branch?
When did you download the script. Scott made a change 27 days ago, maybe it fixes your issue?

**Comment by sidi762** [comment]
Hi Nikolai,

I downloaded it earlier today, 2.80 branch.

I just uninstalled 2.82 and reinstalled 2.81 and it worked.

Kind regards,
Sidi

**Comment by NikolaiVChr** [comment]
Well, it still needs looking into.
I will see if I can reproduce.

**Comment by NikolaiVChr** [comment]
I cannot reproduce.

Are you sure you followed the install procedure listed in the 2.80 branch readme?
Notice that "Install an add-on" button don't work for this add-on, as the readme states you have to copy the folder in yourself.

**Comment by sidi762** [comment]
Hi Nikolai,

Yes, and using the same procedure I could get the add-on working on 2.80 and 2.81.

This is not the only add-on that doesn't work on the 2.82 though, FGBlendertools and some other add-ons give the same error.

Kind regards,
Sidi

**Comment by NikolaiVChr** [comment]
Hmm, strange that it worked for me, are you also using Windows?

**Comment by sidi762** [comment]
No, I'm using macOS Mojave.

**Comment by Entamut** [comment]
Hi!
macOS Catalina (10.15.5) and Blender v 2.82.a here and it worked perfectly.
Cheers.

**Comment by sfrsfrsfr** [comment]
Hi,

it seems the plugin is not compatible with Blender 2.83.
In Preferences/Addons it says: 'Upgrade to 2.8x required'.
Any chance of upgrading it?

Bye, Stefan

**Comment by NikolaiVChr** [comment]
Just for information, I talked to @sfrsfrsfr on Discord, and he was using the master (2.79) branch, not the 2.80 branch. So should be good now.

**Comment by sidi762** [comment]
I just tried with 2.91 and it works fine. I think this issue can be closed now. Thanks!
