### ISSUE TITLE
It does not work/detect Blender 2.83, 2.93

### ISSUE THREAD

**Issue by weirdgyn** [NikolaiVChr/Blender-AC3D#27]
Installed on Blender 2.93 64bit (Windows 10):

C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_scene_ac3d

![image](https://user-images.githubusercontent.com/6094578/123072138-925e7e00-d415-11eb-82bd-6066e540fd69.png)

Result:

![image](https://user-images.githubusercontent.com/6094578/123072226-a4402100-d415-11eb-85ef-e3a34dcff000.png)

Same problem running it on Blender 2.83.

**Comment by NikolaiVChr** [comment]
You downloaded the wrong version.

Download branch 2.80 not master.

**Comment by weirdgyn** [comment]
I see... I tought github provided a different uri for the 2.80 branch... but it does not!
Thanks! This plugin is wonderful !
