### ISSUE TITLE
hwo to  batch import ac3d?

### ISSUE THREAD

**Issue by unsanedingding** [NikolaiVChr/Blender-AC3D#28]
![微信图片_20210907131007](https://user-images.githubusercontent.com/26058055/132287638-9d09ccee-9977-4d86-9754-3c350eb094f1.png)
I test one file import in "for" loop, but if i have more than one .ac3d file in for loop, the import result is error. Why?

**Comment by NikolaiVChr** [comment]
Hmm, good question. Not sure why it doesn't work.
