### ISSUE TITLE
"axis" SubModel of f16 cockpit   degenerate a point in Blender

### ISSUE THREAD

**Issue by unsanedingding** [NikolaiVChr/Blender-AC3D#29]
I use the plugin, I notice some subModel object degenerated a 3d point ,eg. "Cockpit\Main\misc\laser-arm-switch-axis", in fact ,all of about 'axis'  model  will degenerate a 3d point in F16 . So, what should do?

**Comment by NikolaiVChr** [comment]
When you export there is an option to export lines, check that.
