### ISSUE TITLE
Exported object segfaults Intel Mesa driver

### ISSUE THREAD

**Issue by onox** [NikolaiVChr/Blender-AC3D#3]
I'm trying to export `Resources/WIP/canopy-6-FITTINGS.blend`. The object `canopyLowerSkin` (when it becomes visible by pressing "v" key) crashes FG via a segfault in the video driver.

I have reduced the data of the object to the following:

```
OBJECT poly
name "canopyLowerSkin"
data 12
Cylinder.211
loc 2.9930539 0.2669726 0.0660472
crease 64.0
numvert 2
-0.02493 0.16040 -0.40419
0.02446 0.16613 -0.40753
numsurf 1
SURF 0X30
mat 0
refs 3
1 0.183005 0.442966
0 0.184468 0.437419
1 0.187719 0.437412
kids 0
```

Two vertices above causes immediate crash. Two vertices below crashes
when zooming in a lot (in Helicopter View)

-0.02716 -0.03345 -0.01403
-0.02716 -0.03345 -0.01086

I'm not really familiar with the AC3D format. I suppose the two numbers in the SURF section are the UV coordinates?

**Comment by NikolaiVChr** [comment]
Its trying to make a face from only 2 vertices, thats not good.

If this was imported from a AC3D, could you try paste here the original "canopyLowerSkin"?

And yes the 2 numbers on the left under refs 3 is reference to which vertex to use, the number right of that is the UV coordinates.

**Comment by onox** [comment]
The actual exported object consists of faces from 3 vertices. I just started removing indices and vertices to the bare minimum.

**Comment by onox** [comment]
Here's the `canopy.ac` file with just the `canopyLowerSkin` object exported: [canopy.zip](https://github.com/NikolaiVChr/Blender-AC3D/files/553870/canopy.zip)

**Comment by NikolaiVChr** [comment]
Not sure I follow.

Did it crash already with the 1291 vertices? And then you kept removing vertices to figure out what made it crash?

**Comment by onox** [comment]
Yes.

**Comment by NikolaiVChr** [comment]
Roger, will test.

**Comment by onox** [comment]
I'm inspecting the difference between the original `canopy.ac` and the newly exported one, and it seems the original contains:

```
texture "enclosure.png"
texrep 1 1
```

**Comment by NikolaiVChr** [comment]
I am on discord, then we can talk better about it.

**Comment by NikolaiVChr** [comment]
Okay, some issue resolved. However the crash still puzzles me, as it doesn't crash for me. Will leave this bug open.

**Comment by NikolaiVChr** [comment]
Closing this for now. If it gives you trouble in Flightgear again, you can reopen the issue.
