### ISSUE TITLE
Not working on Blender 2.83 LTS

### ISSUE THREAD

**Issue by ghost** [NikolaiVChr/Blender-AC3D#30]
I followed instructions but it's not working. Maybe I need to install different version of Blender?

**Comment by SammySkycrafts** [comment]
What do you mean by "Its not working"? Are you using the correct branch (take a look at the `README.md`)Are there any error messages?

I have just tested with Blender 2.83LTS and it is working fine.

**Comment by ghost** [comment]
I pasted file to addons folder and on addons list I couldn't see it. I tried install manually by "install" button but still same. Seems like problem on me.
