### ISSUE TITLE
is this support blender3.2?

### ISSUE THREAD

**Issue by super-xxx** [NikolaiVChr/Blender-AC3D#31]
i have notice that the latest version of blender is 3.2, is this tool support blender3.2?

**Comment by NikolaiVChr** [comment]
Not yet

**Comment by NikolaiVChr** [comment]
Started a branch to support 3.2
https://github.com/NikolaiVChr/Blender-AC3D/tree/3.2

Still untested

**Comment by malespiaut** [comment]
I can confirm that the 3.2 branch works for importing models in Blender v3.3.

**Comment by kolos26** [comment]
I got this error, when I tried to enable it on 3.4
`Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'Blender-AC3D-3'`
How can I fix it?

**Comment by NikolaiVChr** [comment]
Did you download the 3.2 branch? The master branch is for 2.79.

**Comment by kolos26** [comment]
Thank you for your quick reply! I'm using the 3.2 branch

**Comment by NikolaiVChr** [comment]
There is now also a 4.0 branch.
Closing this issue.
