### ISSUE TITLE
Error trying to export ac3D file using Blender

### ISSUE THREAD

**Issue by 24lavsri** [NikolaiVChr/Blender-AC3D#36]
Getting below error when exporting ac3d from Blender to Flight gear. The add on is enabled in Blender. 

Python: Traceback (most recent call last):
  File "C:\Users\lavis\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\ac3d addon\__init__.py", line 359, in execute
    from . import export_ac3d
ImportError: cannot import name 'export_ac3d' from 'ac3d addon' (C:\Users\lavis\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\ac3d addon\__init__.py)

**Comment by NikolaiVChr** [comment]
Which branch of the export tool did you download and use?

**Comment by 24lavsri** [comment]
https://github.com/NikolaiVChr/Blender-AC3D/tree/4.0
This is what I used.

**Comment by NikolaiVChr** [comment]
There is now a 4.1 branch

**Comment by 24lavsri** [comment]
ok thank you
