### ISSUE TITLE
Bad material color exported from blender 4.1

### ISSUE THREAD

**Issue by klnavajo** [NikolaiVChr/Blender-AC3D#38]
Sorry, I have found another problem with the export of `MATERIAL` rgb…

With **Blender 4.1** + **BSDF Principled**:

![shot-2024-06-13_11-43-02](https://github.com/NikolaiVChr/Blender-AC3D/assets/42573718/b5ffeba1-1330-4224-807d-8ef87e701778)

The `rgb` (and `spec`, and perhaps some others) values seems take default value !? (_AC3D.py l.750 ?_)

P.S. same issue with _Blender-AC3D-4.1_

**Comment by NikolaiVChr** [comment]
Yes,
Blender 2.80 or later has no support for AC3D material model.
In BSDF Principled, rgb is normally a albedo-texture, which AC3D does not support. But if no texture is mounted, the color value is exported.
EEVEE_SPECULAR is the material node that comes closest to AC3D, in the import settings you can choose that.

If you want (almost) full material support, use Blender 2.79

**Comment by klnavajo** [comment]
Ok, thks.
