### ISSUE TITLE
wrong local matrix

### ISSUE THREAD

**Issue by alphamikeuniform** [NikolaiVChr/Blender-AC3D#5]
https://github.com/NikolaiVChr/Blender-AC3D/blob/16082b46c888a8d1420e14bdd8e0d9c5350f3448/io_scene_ac3d/AC3D.py#L44

I think this line should read
 
`localMatrix = bl_obj.matrix_local`

`matrix_local` already contains `matrix_parent_inverse` because the following applies:
`matrix_local = matrix_parent_inverse * matrix_basis`
`matrix_basis` is the transformation defined by the object transform properties window
`matrix_parent_inverse` is the inverse of the parents world matrix at the time of parenting

**Comment by NikolaiVChr** [comment]
Yes, is what I initially thought too. But some experimentation showed this to work.
If you can make a little test file that will fail with the current code, I will look into it again.

**Comment by alphamikeuniform** [comment]
I created a simple example with two boxes. The (bigger) parent box is at (world) position (0,0,3), the (smaller) child box is at (world) position (0,0,5). The parent inverse matrix of the child box is the translation (0,0,-3).
I exported with option Matrices = Export.

[ac_test.zip](https://github.com/NikolaiVChr/Blender-AC3D/files/1720771/ac_test.zip)

**Comment by NikolaiVChr** [comment]
Just to be sure. Latest version of Blender?

**Comment by NikolaiVChr** [comment]
You are right.
Modified the test case to include rotation and scaling also, and at very least it now imports the same as it exports.
Not sure how I did not catch this, did tons of tests.

Thanks. If you find any other errors, your feedback is welcome.

**Comment by NikolaiVChr** [comment]
Fixed in v2.24.
